apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-service-config
  namespace: community-issues
data:
  USER_SERVICE_URL: http://auth-service.community-issues.svc.cluster.local:8000
  NOTIFICATION_SERVICE_URL: http://notification-service.community-issues.svc.cluster.local:8000
