apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-service
  namespace: community-issues
  labels:
    app: issue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issue-service
  template:
    metadata:
      labels:
        app: issue-service
    spec:
      containers:
        - name: issue-service
          image: docker.io/22i1167x/issue-service:13e7541f8d5864a1e4f5b10da36319fd6b84143f
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: issue-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
